"""add column

Revision ID: 48fea2f20113
Revises: 
Create Date: 2022-02-27 18:03:44.168957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fea2f20113'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests2', sa.Column('notes', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests2', 'notes')
    # ### end Alembic commands ###
